# Services
services:
  # PHP FPM Service
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - 89:80
    links:
      - php
    volumes:
      - './:/var/www/html'
      - './docker:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass
      MYSQL_ROOT_PASSWORD: R00tp@ss
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3308:3306

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mariadb        
      PMA_USER: root             
      PMA_PASSWORD: R00tp@ss     
    ports:
      - "1088:80"                
    depends_on:
      - mariadb

volumes:
  mariadb_data:
